### ISSUE TITLE
CH Core Composition Profile EPR (oe)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#110]
ch.fhir.ig.ch-core#1.3.0 /StructureDefinition-ch-core-composition-epr.html

author reference to CH Core Practitioner Role Profile should be CH Core Practitioner Role Profile EPR

oe

**Comment by ziegm** [comment]
the same for the reference of "Composition.attester.party:legalAuthenticator"

**Comment by ziegm** [comment]
[Actual CH Core Composition Profile EPR](https://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition-epr.html)

--> [Updated CH Core Composition Profile EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue110/StructureDefinition-ch-core-composition-epr.html) (or see [Commit](https://github.com/hl7ch/ch-core/commit/6bf064ad3529a72cb8977218595d58000f47907b))

**Comment by oliveregger** [comment]
Kann so bereinigt werden 9 - 0 - 0
