### ISSUE TITLE
CH Core Practitioner Role Profile EPR is not displayed in the tab "Profiles" (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#111]
The [CH Core Practitioner Role Profile EPR](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-practitionerrole-epr.html) is listed in the tab [Artifacts](http://fhir.ch/ig/ch-core/artifacts.html), but not in the tab [Profiles](http://fhir.ch/ig/ch-core/profiles.html). Should be listed there as well.

**Comment by ziegm** [comment]
In the actual CI build the **CH Core Practitioner Role Profile EPR** is displayed in the tab [Profiles](http://build.fhir.org/ig/hl7ch/ch-core/profiles.html).

**Comment by oliveregger** [comment]
kann geschlossen 9-0-0
