### ISSUE TITLE
CH Core Composition Profile EPR -> Cardinalities of identifier.system and value (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#112]
[CH Core Composition Profile EPR](http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-composition-epr.html)
Update the minimum cardinality of Composition.identifier.system and Composition.identifier.value to 1 instead of 0.    

Equivalent to the identifier in the [document profile](http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-document.html).

**Comment by oliveregger** [comment]
kann so geschlossen werden 9-0-0
