### ISSUE TITLE
CH Core Coverage Profile - Proposal (Felizitas Wahl-Homner, CISTEC AG)

### ISSUE THREAD

**Issue by wahlfe** [hl7ch/ch-core#116]
**Implementation Guide**
ch.fhir.ig.ch-core#2.0.0 /StructureDefinition-ch-core-coverage.html

**coverage.type**
 http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-coverage-definitions.html#Coverage.type 
 should have a binding on a swiss value set; attached proposal: 
-  CISTEC_CodeSystem-CH-Core-HealthCoverageTypeCode-CodeSystem_20210526.xlsx

Please consider, to use the abbreviations OKP, UV, MV, etc. as proposed in the file, because it is common practice within the Swiss health system. Furthermore, the BfS-Code doesn't cover VVG/Zusatzversicherung for it isn't used within the BfS-statistics. 

**coverage.class.type** 
http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-coverage-definitions.html#Coverage.class.type 
should have a binding on a swiss value set; attached proposal: 
- CISTEC_CodeSystem-CH-Core-HealthCoverageClasseCode-CodeSystem_20210526.xlsx

Please consider, to use the abbreviations A, HP, P as proposed in the file, because it is common practice within the Swiss health system. Furthermore, the BfS-Code doesn't provide enough codes for today's insurance coverages.

Kind regards
Felizitas Wahl-Homner
CISTEC AG

[CISTEC_CodeSystem-CH-Core-HealthCoverageClassCode-CodeSystem_20210526.xlsx](https://github.com/hl7ch/ch-core/files/6546621/CISTEC_CodeSystem-CH-Core-HealthCoverageClassCode-CodeSystem_20210526.xlsx)

[CISTEC_CodeSystem-CH-Core-HealthCoverageTypeCode-CodeSystem_20210526.xlsx](https://github.com/hl7ch/ch-core/files/6546624/CISTEC_CodeSystem-CH-Core-HealthCoverageTypeCode-CodeSystem_20210526.xlsx)

**Comment by oliveregger** [comment]
Abhängig von Entwicklungen auch in http://build.fhir.org/ig/hl7ch/ch-orf/StructureDefinition-ch-orf-coverage.html

**Comment by oliveregger** [comment]
http://fhir.ch/ig/ch-core/ValueSet-bfs-medstats-21-encountertype.html

**Comment by oliveregger** [comment]
related also to https://github.com/hl7ch/ch-orf/issues/80

**Comment by ziegm** [comment]
**Proposal Coverage.type:**
- add CodeSystem-bfs-medstats-25-mainguarantor (to avoid introducing new codes) and CodeSystem-mainguarantor for the missing value, which is used also in CH ORF and other known use cases
- CH ORF should do an update to use these codes (https://github.com/hl7ch/ch-orf/issues/173)
- ![image](https://github.com/hl7ch/ch-core/assets/32767151/75041b29-399c-4299-91d3-867053f05a76)


**Proposal Coverage.class.type:**
- use the already existing ValueSet-bfs-medstats-21-encountertype, to avoid introducing new codes
- the proposed value "others" is not included, no explicit use case is known (could be added later if needed)
- ![image](https://github.com/hl7ch/ch-core/assets/32767151/b8d56e18-ba02-441c-a6d6-0648bb895c8c)

**Comment by ziegm** [comment]
24.04.2024 FHIR Telco:
- discussion why using the BFS numbers
- new introduced in CH Core (impact on CH ORF)
   - binding not required
- discussion about "other" (included in one and not in the other)

Proposal for CH ORF
- reduce the binding strenght to extensible (from required) 

Vote: 13 - 0 - 1
Negative comment: seems like an adhoc solution, may there are international solutions, other resources would be use (e.g. InsurancePlan)
