### ISSUE TITLE
CH EPR mHealth IG - Various issues

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-core#117]
I've completed a review of the following profiles focused on the MHD-XDS conversion:

- [StructureDefinition: IHE_MHD_Comprehensive_DocumentManifest_CH](http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-mhd-comprehensive-documentmanifest.html) (current v0.1.2)
- [Resource Profile: CH MHD DocumentReference Comprehensive](http://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/StructureDefinition-ch-mhd-documentreference-comprehensive.html) (draft v0.2.0)

The mapping guides:

- [DocumentManifest-SubmissionSet mapping](https://qligier.github.io/ch-epr/DocumentManifest-SubmissionSet%20mapping.html)
- [DocumentReference-DocumentEntry mapping](https://qligier.github.io/ch-epr/DocumentReference-DocumentEntry%20mapping.html)

I've found multiple issues that prevent converting between MHD and XDS resources and getting a valid result, per the Swiss specifications. Other conversion issues may or may not be in scope of the CH-Core/CH-EPR-mHealth IGs.
Cardinalities are reviewed at the bottom of both guides and incompatibilities are highlighted.

Some elements are marked as "Must support", should we make sure these are mapped when implementing a converter?
My plan was to focus only on required elements in the first time, but some optional elements are marked as "Must support", so that would change my implementation scope a bit.

**Comment by qligier** [comment]
I see that there's a new draft of these profiles (v0.2.0) and wanted to update the mapping guides to that version, but the DocumentManifest profile seems to be quite worst than the current version (0.1.2). I've seen a lot of breaking, pointless changes that are not applied to the DocumentReference profile, so I'm wondering about its status.
I'll only update the DocumentReference mapping guide, as I've only see a few changes that should improve the profile.

**Comment by oliveregger** [comment]
@qligier thanks for your feedback, I think the issues you mentioned are concerning the  ch-epr-mhealth implementation guide? if yes can you note the issues there? you find the current version as the CI Build here:
http://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/index.html at the bottom is a Propose a Feedback change link or you open it directly as an issue in the repo of ehealth suisse.

Mid June will be a version published which will be used for testing at the swiss projectathon in september, so if things can be improved input/feedback is highly welcomed: https://github.com/ehealthsuisse/ch-epr-mhealth/issues

**Comment by qligier** [comment]
Sure yes, thanks! The published version is missing the Propose a change link and it says it's part of CH-Core and I've not seen the draft was different, so I opened it here. I'll move it to [ehealthsuisse/ch-epr-mhealth](https://github.com/ehealthsuisse/ch-epr-mhealth/issues).
