### ISSUE TITLE
Description of best practice on how to author a Swiss FHIR IG

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#120]
Es wurde diskutiert, dass man Best Practices über das Erstellen von Schweizer IGs erstellen soll (ursprünglich aufgekommen bei den Referenzen zu anderen Profilen).
Wo soll dokumentiert werden?
Was soll alles beschrieben werden?

**Comment by oliveregger** [comment]
Started a new page on the wiki: https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Developments
