### ISSUE TITLE
CH Core Composition EPR Custodian Cardinality

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-core#121]
In the [CH Core Composition Profile EPR](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition-epr.html), the cardinality of the custodian is set to 1..1.

This means that a custodian reference to an organization always has to be set.
In cases the patient will upload data to the EPR (i.e. vaccination) there will be a problem, that there is no organization to be set.
From this point of view, the cardinatlity has to be reset to the basic or an other solution for the organization problem has to be described.

**Comment by oliveregger** [comment]
Annatina: Nicht notwendig aus Sicht EPD
Historisch aus Kompatibilität CDA-CH (In der eMedikation müsste dass dann aber wieder eingeführt werden)

Entscheid: so umsetzen: 14-0-0
