### ISSUE TITLE
No fixed value for Status of Composition -- CH Core Composition Profile EPR (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#122]
ch.fhir.ig.ch-core#2.0.0 /StructureDefinition-ch-core-composition-epr.html

Currently, value of composition.status is fixed to "final" in ChCoreCompositionEPR. This restriction should be removed and set back to "Binding: CompositionStatus (required)" as it is in ChCoreComposition as well.
Reason: The detail concept of "eVaccination in the EPR" makes use of the status "entered-in-error" for document annullation. 

Annatina Foppa, eHealth Suisse

**Comment by oliveregger** [comment]
Bedingung kann aufgehoben werden: 15 - 0 - 0
