### ISSUE TITLE
gln and epr-spid checks

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#123]
ch.fhir.ig.ch-core#2.0.0 /NamingSystem-gln.html

add gln rules form jens / dk, se  https://hl7.dk/fhir/core/1.1.0/StructureDefinition-dk-core-gln-identifier.html

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
syntax check kann entsprechend so übernommen werden

**Comment by oliveregger** [comment]
additionally syntax check for epr-spid

**Comment by oliveregger** [comment]
ergänzen für AHV Nummer mit 13 Stellen und Start 756
Link 

https://www.bsv.admin.ch/bsv/de/home/sozialversicherungen/ahv/grundlagen-gesetze/ahv-nummer.html
https://www.sozialversicherungsnummer.ch/aufbau-neu.htm
