### ISSUE TITLE
CH Core Practitioner und NIF?

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#126]
NamingSystem OID für NIF-Nummer? 

Wir die dem Arzt zugeteilt oder gehört sie in die Coverage Resource?

https://www.iv-pro-medico.ch/glossar/detail/nif-nummer/?tx_contaged_listcontagged%5Baction%5D=show&cHash=a35071de3270191c7153ea528114e139

Wird gebraucht zur Abrechnung mit der Invalidenverbindung

**Comment by oliveregger** [comment]
Piet: https://www.zas.admin.ch/zas/de/home/partenaires-et-institutions-/paiement-des-prestations-individuelles-avs-ai/information-a-l-attention-des-fournisseurs-de-prestations.html

**Comment by ziegm** [comment]
Gemäss diesem Text eher dem Practitioner:

_3.3.5 nif - Identifikationsnummer des Leistungserbringers
Sämtliche von der IV anerkannten Rechnungssteller erhalten zusätzlich zur GLN spätestens bei der
ersten Rechnungsstellung für die IV noch eine Identifikationsnummer NIF (numéro d'identification du
fournisseur, vergleichbar mit der ZSR-Nummer von santésuisse). Unter dieser Nummer werden die
Informationen zu den Zahlungsadressen abgespeichert. Es ist ratsam, vor der ersten
Rechnungsstellung mit der ZAS Kontakt aufzunehmen (E-Mail an sachleistungen@zas.admin.ch) und
die GLN des Leistungserbringers (sowie vorläufig die IBAN) anzugeben. Dies ermöglicht die
Erstellung einer neuen NIF._

Quelle: https://www.zas.admin.ch/dam/zas/de/dokumente/Partenaires%20et%20institutions/PPI/Dokumentation_elektronische_Rechnungsstellung_v1_3_public_2.pdf.download.pdf/Dokumentation_elektronische_Rechnungsstellung_v1_3_public_2.pdf

**Comment by ziegm** [comment]
Note: We already defined a NamingSystem for NIF, but had to uncomment it because of the missing uniqueId:
https://github.com/hl7ch/ch-core/blob/f9ca39f268b3db787d0d272e1887ed5a0417d867/sushi-config.yaml#L97

**Comment by lpg-tech** [comment]
We could propose the IV-Stellen-Konferenz to ask for an OID, or alternativly replace the NIF with ZSR or GTIN:
IV-Stellen-Konferenz
Geschäftsstelle
Sempacherstrasse 15
6003 Luzern
info@ivsk.ch
041 361 60 21

**Comment by oliveregger** [comment]
Discussion if it is actually used anymore. 
Put in on hold until we get feedback that we should represent it wit an oid in ch-core.

10 - 0 -0

**Comment by lpg-tech** [comment]
From the The Federal Department of Finance (FDF) is the following answer:
Besten Dank für Ihre Frage. Die NIF ist effektiv nicht mehr nötig für die Abrechnung. 

Freundliche Grüsse

Antonella Gonnella
Spécialiste paiement  des prestations individuelles AVS/AI
Spezialistin Zahlung individueller Leistungen AHV/AI

Département fédéral des finances DFF
Centrale de Compensation CdC
Finances et Registres centraux FRC

Avenue Edmond-Vaucher 18, CP 3000, CH-1211 Genève 2
Tél. +41 58 461 95 09
Fax +41 58 461 93 32
mailto:antonella.gonnella@zas.admin.ch
http:// www.zas.amdin.ch

**Comment by ziegm** [comment]
> From the The Federal Department of Finance (FDF) is the following answer: Besten Dank für Ihre Frage. Die NIF ist effektiv nicht mehr nötig für die Abrechnung.

Can we close the issue then?

**Comment by oliveregger** [comment]
remove it and close the issue

**Comment by ziegm** [comment]
already removed
