### ISSUE TITLE
add an Identifier data type for AHVN13 with check for correctness

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#135]
Like we added an identifier data type for GLN and EPR-SPID the AHVN13 should also be added as an identifier data type with the check (see related https://github.com/hl7ch/ch-core/issues/123)

ergänzen für AHV Nummer mit 13 Stellen und Start 756:
https://www.bsv.admin.ch/bsv/de/home/sozialversicherungen/ahv/grundlagen-gesetze/ahv-nummer.html
https://www.sozialversicherungsnummer.ch/aufbau-neu.htm

**Comment by ziegm** [comment]
In which format is the AHV number exchanged? With and/or without dots between the digits?

**Comment by oliveregger** [comment]
- CH PPQ und PPQm sowie eCH Schnittstellen ist die AHV Nummer ohne Punkt

**Comment by oliveregger** [comment]
add a description that the AHVN number is transmitted without points and enforced as a constraint. 14-0-0
