### ISSUE TITLE
Typo: communication:languageOfCorrespondance	 (Michaela Ziegler, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#142]
ch.fhir.ig.ch-core#2.0.0 /StructureDefinition-ch-core-patient.html

communication:languageOfCorrespondence 

Michaela Ziegler, ahdis

**Comment by ziegm** [comment]
related to https://github.com/hl7ch/ch-orf/issues/105

**Comment by ziegm** [comment]
Source: eCH 
3.3.9 languageOfCorrespondance
https://www.ech.ch/de/dokument/7f72f89f-d1e9-49f5-98cd-6ccf1a84065d

**Comment by ziegm** [comment]
fixed typo: http://build.fhir.org/ig/hl7ch/ch-core/branches/issue142/StructureDefinition-ch-core-patient.html

**Comment by ziegm** [comment]
HL7 Telco: 11-0-0
