### ISSUE TITLE
Extension EPR Time: Expand context (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#150]
ch.fhir.ig.ch-core#2.1.0 /StructureDefinition-ch-ext-epr-time.html

According to this Issue in CH EMED (https://github.com/hl7ch/ch-emed/issues/113), an expansion of the context is necessary:
- Observation.extension
- Observation.performer
- MedicationDispense.extension
- MedicationDispense.performer.actor
- MedicationRequest.extension
- MedicationRequest.performer
- Extension.valueReference

Michaela Ziegler, ahdis ag

**Comment by oliveregger** [comment]
discussed at telco at 9/28/22, will be integrated after ballot voting is through: 12 -0 - 0
