### ISSUE TITLE
AHVN13 / NAVS13 Identifier - JSON Representation (Oliver Egger, ahdis.ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#152]
ch.fhir.ig.ch-core#2.1.0 /StructureDefinition-ch-core-ahvn13-identifier.profile.json.html

1. The tab json does not show up as in http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-ahvn13-identifier.profile.json.html
2. "status" : "draft" -> should be active as the others

same applies to: StructureDefinition-ch-core-gln-identifier.profile.json.html, StructureDefinition-ch-core-epr-spid-identifier.profile.json.html

Oliver Egger, ahdis.ag

**Comment by ziegm** [comment]
### HL7.ch FHIR Telco 12.10.2022
Proposal to approve the resolution of the issue in the block vote.

**Summary:** 
* status change from draft to active
   * json tab appears now
* issue listed in [change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/changelog.html)

**Comment by ziegm** [comment]
Accepted with block vote, 12.10.2022 (see [wiki](https://github.com/hl7ch/ch-core/wiki#wed-12102022-200-pm---300-pm))
