### ISSUE TITLE
Home: Exchange formats (Annex 4) (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#153]
ch.fhir.ig.ch-core#2.1.0 /

"There are currently three exchange formats defined in the draft of Annex 4. Those three exchange formats are based on CDA-CH V2."

Update to the current status:
* two (?) exchange formats (https://www.e-health-suisse.ch/technik-semantik/semantische-interoperabilitaet/austauschformate.html)
* CDA-CH V2: only eMedication

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
Annex 4 will include the CH EMED, CDA-CH-EMED, and CH VACD exchange formats.

**Comment by ziegm** [comment]
Exchange formats for the Swiss EPR are defined in Annex 4. Exchange formats can be represented as FHIR documents.

**Comment by ziegm** [comment]
### HL7.ch FHIR Telco 12.10.2022
Proposal to approve the resolution of the issue in the block vote.

**Summary:** 
* update intro to exchange formats (annex 4) at home page
* issue listed in [change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/changelog.html)
