### ISSUE TITLE
Example Instances: improve description (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#154]
ch.fhir.ig.ch-core#2.1.0 /artifacts.html

For faster search of certain examples (e.g. patient with local PID as identifier) it would be good to adjust the descriptions of the examples (it already has some good examples).

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
### HL7.ch FHIR Telco 12.10.2022
Proposal to approve the resolution of the issue in the block vote.

**Summary:** 
* improve the description, see [here](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/artifacts.html#8)
* issue listed in [change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/changelog.html)

**Comment by ziegm** [comment]
Feedback to block vote from Gabriel Hess, 10.10.:
Beim Issue #154 / PR #177, in [input/examples/practitioner/SchreibKraft.xml](https://github.com/hl7ch/ch-core/issues/154#diff-4c231b67809a63f7b682168dee3d15fff6956b0085e05d6366ff9cc607982738): “local identifier” wäre konsistenter als “local Identifier”

**Comment by ziegm** [comment]
Accepted with block vote, 12.10.2022 (see [wiki](https://github.com/hl7ch/ch-core/wiki#wed-12102022-200-pm---300-pm))
