### ISSUE TITLE
Guidelines for Swiss IG Development: Publication on fhir.ch

### ISSUE THREAD

**Issue by heg2** [hl7ch/ch-core#156]
Github is changed from using `main` instead of `master` for default the default branch in a new project (see https://github.com/github/renaming). Yet, the guideline for Swiss IG demands the default branch to be `master` for pipeline compatibility.

With a long-term perspective, it could make sense to adjust the publication pipeline (and thus the existing IGs) for using `main` as the default branch.

**Comment by ziegm** [comment]
see also discussion on [zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Publisher.20using.20master.20OR.20main)

**Comment by ziegm** [comment]
### HL7.ch FHIR Telco 12.10.2022
Proposal to approve the resolution of the issue in the block vote.

**Summary:** 
* At the moment it still has dependencies/impacts in the context of using IG Publisher (see discussion on zulip). As soon as there has been this further development with the IG Publisher, it can be resumed.
* issue listed in [change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/changelog.html)

**Comment by ziegm** [comment]
Accepted with block vote, 12.10.2022 (see [wiki](https://github.com/hl7ch/ch-core/wiki#wed-12102022-200-pm---300-pm))
