### ISSUE TITLE
FHIR-Release, auf welches CH Core basiert (Emmanuel Eschmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#158]
ch.fhir.ig.ch-core#2.1.0 /

CH Core bezieht sich auf FHIR v4.0.1. Es wäre wünschenswert, die aktuelle oder sonst zumindest die nächste Version von CH Core auf den aktuelleren Release FHIR v4.3.0 basieren zu lassen.

Emmanuel Eschmann

**Comment by ziegm** [comment]
Telco 12.10.:
OE: IHE wird alles weiter unter R4 publizieren, höchsten es wären R4B-Elemente/Ressourcen notwendig für den entsprechenden Fall.

**Comment by oliveregger** [comment]
Der IG Publisher in Zukunft die Möglichkeit haben dass sowohl ein R4 wie auch ein R4B Package publiziert wird, siehe hier:
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/R4.20.2F.20R4B.20IGs

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_versions/index.html#cross-version-analysis

Cross Version Analysis
This is an R4 IG. None of the features it uses are changed from R4B, so it can be used as is with R4B systems. Packages for both [R4 (ch.fhir.ig.ch-core.r4)](http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_versions/package.r4.tgz) and [R4B (ch.fhir.ig.ch-core.r4b)](http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_versions/package.r4b.tgz) are available.

@EmmanuelEschmann passt das so? CH Core kann aktuell sowohl für R4 und R4B verwendet werden, und es stehen für beide Versionen Packages zu Verfügung.

**Comment by EmmanuelEschmann** [comment]
Hallo @oliveregger ,
Ja danke, das passt so, wenn im IG sichtbar ist, dass CH Core sowohl für R4 als auch für R4B verwendet werden kann.

**Comment by oliveregger** [comment]
Implement like that: 10 - 0 - 0
