### ISSUE TITLE
CH Core Consent EPR: typo (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#163]
ch.fhir.ig.ch-core#2.1.0 /StructureDefinition-ch-core-consent-epr.html

Excluded encounter for EP -> EPR

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
### HL7.ch FHIR Telco 12.10.2022
Proposal to approve the resolution of the issue in the block vote.

**Summary:** 
* fixed typo
* issue listed in [change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/changelog.html)
