### ISSUE TITLE
Extension for Author (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#172]
ch.fhir.ig.ch-core#2.1.0 /

In the IG for ch-emed and ch-vacd, there are extensions defined with the same meaning but for different resources.
Would it not be a good idea, to define a generic ch-core extension to be usable in different contexts?
see:
* http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-documentauthor.html
* http://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-ext-immunization-recorder-reference.html

Roeland Luykx (RALY GmbH)

**Comment by ziegm** [comment]
In CH EMED is an open issue to change this extension: https://github.com/hl7ch/ch-emed/issues/114
proposal: http://build.fhir.org/ig/hl7ch/ch-emed/branches/projectathon2022/StructureDefinition-ch-emed-ext-documentauthor.html

CH EMED: Reference(CH EMED PractitionerRole)
CH VACD: Reference(CH Core Patient | CH Core PractitionerRole | RelatedPerson)

**Comment by ziegm** [comment]
Proposal to discuss @ telco:
[Extension: Author of the content](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue172_ext-author/StructureDefinition-ch-ext-author.html)

**Comment by ziegm** [comment]
Telco 12.10.2022:
Diskussion Konzepte 'Data Enterer' und 'Author of the content'. Unterschiedliche Kontexte, Gebrauch in Composition vs. MedStat/Disp/Req/Observation/Immunization.
Voting: 7-0-0
