### ISSUE TITLE
EPR in Title: why (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#175]
ch.fhir.ig.ch-core#2.1.0 /StructureDefinition-ch-core-consent-epr.html

The profile does not refers to no EPR resources. thus may the name of the profile without EPR, or the References shoudl be pointed to EPR resource profiles.

Roeland Luykx (RALY GmbH)

**Comment by ralych** [comment]
der titel war für mich in ordnung sofern die anderen referenzen auch auf EPR zeigen. tun sie aber nicht.
![Screenshot from 2022-10-11 13-18-03](https://user-images.githubusercontent.com/75606442/195077969-b08d23d7-548e-41ac-86a3-f78e65139d27.png)
patient zeigt auf CH Core Patient
performer auf CH Core... Organization, Patient, Practitioner, Practitioner

EPR consent ist es ja prinzipiell nur wegen dem fixen wert policyRule der auf ch-epr lautet.

Entweder wir haben einen CH Core Consent mit den CH Core profilen oder einen CH Core EPR Consent mit den CH Core EPR profilen.

**Comment by ziegm** [comment]
Rücksprache mit Roeland, 11.10.:

Umbenennung im Vorschlag zu 'EPR-Consent' klar, weil der value fix für **ch-epr** ist.
http://build.fhir.org/ig/hl7ch/ch-core/branches/stu3-ballot_resolution/StructureDefinition-ch-core-epr-consent.html

Was noch offen ist, ob es ein EPR Profil sein soll?
Wenn ja, soll das im Titel wieder ergänzt werden (wie vorher) und die Referenzen auf EPR-Profile gewechselt werden.

**Comment by ziegm** [comment]
Telco 12.10.:
Hintergrund: Man will dokumentieren, ob der Patient ein EPD hat oder nicht, dies unabhängig eines EPD-Dokuments. Daher nicht als EPR-Profile abgebildet.

**Comment by oliveregger** [comment]
@ralych Konntest Du das schon anschauen mit dem Kommentar von der Telco? Können wir das so auf die Agenda für Mittwoch nehmen?

**Comment by ralych** [comment]
Zu bedenken ist, dass man ein profil mach für einen speziellen Use-Case. d.h. bei einem andere Use-Case macht man dann ein anderes profil und der unterschied ist eigentlich dann nur der fixe "wert" des codes.

wenn das nicht problematisch ist, dann ist es von mir aus ok.

**Comment by oliveregger** [comment]
Telco; sieht aktuell niemand als problematisch an 11 - 0 - 0
