### ISSUE TITLE
CH Core Composition EPR: Relax information recipient cardinality

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-core#188]
In [CH Core Composition EPR](http://fhir.ch/ig/ch-core/2.1.0/StructureDefinition-ch-core-composition-epr.html), the information recipient is 1..*. In the context of the EPR, it doesn't make much sense since it's specifically a broadcast, not a specific, targeted communication.

Putting the patient as information recipient is superfluous, since the document is uploaded to their record. Putting one of the EPR community doesn't make sense either, since other communities can access it too.

The cardinality should be relaxed to 0..*.

**Comment by ziegm** [comment]
https://github.com/hl7ch/ch-core/issues/193

**Comment by oliveregger** [comment]
Vorschlag angenommen, entsprechend umsetzen: 8 - 0 - 0
