### ISSUE TITLE
CodeSystem v3-mediaType not known.

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#19]
The code system "http://terminology.hl7.org/CodeSystem/v3-mediaType" in the include in "http://fhir.ch/ig/ch-epr-term/ValueSet/DocumentEntry.mimeType" is not known;

v3-mediaType CodeSystem is not defined by FHIR. Origin of this definition is in CH-EPR-TERM, which is derived from the CH-EPR ART-DECOR project, there it is defined by oid: 2.16.840.1.113883.5.79 - Media Type - urn:oid:2.16.840.1.113883.5.79

**Comment by ziegm** [comment]
Error is no longer present/resolved by IG Publisher
