### ISSUE TITLE
"All slice" constraints do not apply to all slices

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-core#192]
In CHCoreDocument, entry[All Slice].fullUrl is constrained (1..1 and ch-core-doc-1) but these constraints do not appear on other slices.
![2022-11-02 13 24 40 build fhir org 6ff3d29117e8](https://user-images.githubusercontent.com/3299399/199489263-426dd413-835e-4a3d-ad69-4a71fa587835.png)

The differential is also empty:
![2022-11-02 13 24 17 build fhir org 22b90c331acc](https://user-images.githubusercontent.com/3299399/199489273-3c76e887-d98f-4c29-a6cb-c1cc707ab99f.png)

I'd expect them to also be applied to the other slices, since it's called "All Slices" and not "Other Slices".

In CHCoreDocumentEPR, another slice is introduced and it inherits both constraints from entry[All Slice]:
![2022-11-02 13 30 12 build fhir org 5b60b06b4a3f](https://user-images.githubusercontent.com/3299399/199490024-0e78bc2c-5c3e-4412-aa68-615f6a2b65df.png)

Is it a publisher bug or a documented but weird behaviour? In either case, it should be fixed in the profile.

(Note that downstream, if I do a `* entry.fullUrl 1..1`, it applies to all slices as expected)

**Comment by ziegm** [comment]
That's correct, it isn't shown in the defined slices, what you define for all slices (you can also compare it with the [IPS Composition](https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Composition-uv-ips.html)). I understand your expectation, but the publisher shows what we define in the differential: we define for all slices the general rule and then the specific slices. The validator will check the constraints which are defined for all slices for each defined slice.
And changing the profile causes duplicated elements in the snapshot table, see #31. My proposal would be, to leave it like it is.

**Comment by qligier** [comment]
> The validator will check the constraints which are defined for all slices for each defined slice.

Okay, so the validator will apply `ch-core-doc-1` and the 1..1 cardinality to all slices, even if it's not shown in the snapshot? If so, then I guess we can close this issue.

**Comment by ziegm** [comment]
Yes, it will apply to all slices, see test case:
- [Bundle example](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue192_allSliceConstraint/Bundle-1-ZuweisungZurRadiologischenDiagnostik-FHIR.json.html) with wrong url: test.fhir.ch/r4/Composition/ZuweisungZurRadiologischenDiagnostik
- [QA](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue192_allSliceConstraint/qa.html#_scratch_ig-build-temp-EJY2VM_repo_input_examples_bundle_1-ZuweisungZurRadiologischenDiagnostik-FHIR) with error: Rule ch-core-doc-1: 'The fullUrl must be an absolute URL server address or an URI for UUID/OID' Failed

**Comment by qligier** [comment]
Okay, then we can close this issue.
But the IG publisher decision here is really weird and will confuse implementers for sure.

**Comment by ziegm** [comment]
at least takes some getting used to ;-)
