### ISSUE TITLE
relax cardinality of Composition.attester:legalAuthenticator.time

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#194]
set minimum cardinality back to 0, because the requirement due to the CDA requirement is not given anymore
https://build.fhir.org/ig/hl7ch/ch-core//StructureDefinition-ch-core-composition-epr.html

**Comment by ziegm** [comment]
Changes: 
* Profile [CH Core Composition EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/194_authenticator-time/StructureDefinition-ch-core-composition-epr.html) -> Snapshot Table
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-core/branches/194_authenticator-time/changelog.html)

**Comment by oliveregger** [comment]
Ok to proceed like this: 12 -0 -0
