### ISSUE TITLE
CH Core Address - Erweiterung der line um die iso21090-ADXP-streetName (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#195]
ch.fhir.ig.ch-core#2.1.0 /StructureDefinition-ch-core-address.html

Falls es sich bei der Adresszeile um die Strasse handelt wir dort Strasse und Strassennummer angegeben. Es wurde schon die Extension adxp-houseNumber definiert, mit der die Strassenummer explizit angegeben werden kann wie es in eCH auch definiert ist, die explizite Angabe der Strasse ohne Hausnummer fehlt aber (ist aber nicht verbotent). Vorschlag diese Möglichkeit hinzuzufügen wie es auch im deutschen Basisprofil gemacht ist:     

https://ig.fhir.de/basisprofile-de/stable/Ressourcen-Patient.html

```xml
<line value="Musterstraße 1">
        <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber">
            <valueString value="1" />
        </extension>
        <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName">
            <valueString value="Musterstraße" />
        </extension>
    </line>
```

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_195/StructureDefinition-ch-core-address.html

**Comment by oliveregger** [comment]
So umsetzen: 9 - 0 - 0
