### ISSUE TITLE
no 'fixedValues' for display values to avoid warnings in validation (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#200]
(Input originally from CH EMED: https://github.com/hl7ch/ch-emed/issues/194)

We have applied patternCodeableConcepts in some profiles and defined the display value (fixedValue) in addition to the CodeSystem and the code. This causes warnings during validation with examples that include these display values, because they are not the official values as required by http://tx.fhir.org/r4.
When building the IG these warnings can be suppressed.
But if examples are validated against the profile with the validator, the warnings appear. If you change the display values in the examples to the official ones, there are warnings that they do not match the profile.

The proposal is to remove the display values from patternCodeableConcepts or remove fixedValues
* CH Core EPR-Consent - scope / category:VSCat
* CH Core Composition EPR - section.code:originalRepresentation

and relax the minimum cardinality
* CH Core EPR-Consent - category:VSCat	
* Extension EPR Confidentiality Code - valueCodeableConcept.coding.display

**Comment by ziegm** [comment]
Changes:
* [CH Core EPR-Consent](http://build.fhir.org/ig/hl7ch/ch-core/branches/200_display/StructureDefinition-ch-core-epr-consent.html) - scope / category:VSCat
* [CH Core Composition EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/200_display/StructureDefinition-ch-core-composition-epr.html) - section.code:originalRepresentation
* [Extension EPR Confidentiality Code](http://build.fhir.org/ig/hl7ch/ch-core/branches/200_display/StructureDefinition-ch-ext-epr-confidentialitycode.html) - valueCodeableConcept.coding.display
* Updated [example](http://build.fhir.org/ig/hl7ch/ch-core/branches/200_display/Bundle-CdaContainingOriginalRepresentationAsPdfA.xml.html): official values: Normal (qualifier value), Clinical presentation Document
* [Change log](http://build.fhir.org/ig/hl7ch/ch-core/branches/200_display/changelog.html)

**Comment by oliveregger** [comment]
ok to integrate: 12 - 0 - 0
