### ISSUE TITLE
Relax binding strength for value sets (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#215]
ch.fhir.ig.ch-core#3.0.0 /StructureDefinition-ch-core-composition-epr.html

Relax the binding strength to extensible instead of required. If it is required, we are not able to use a newly introduced code, which isn't yet published in CH EPR Term.
- for Composition EPR -> document type
- and check all required bindings

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Changed the binding to the ValueSets from required to **extensible** for the following elements (see [ci build](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue215_bindings/index.html)):
* Composition
   * type
   * confidentiality 
* DocumentReference
   * type
   * category
   * context
      * facilityType 
      * practiceSetting 
* Encounter
   * priority 
   * hospitalization
      * extension:
        * BfsAdmitRole
        * BfsDischargeDecision	
        * BfsDischargeDestination
     *  admitSource
* PractitionerRole
   * specialty
* Patient   
   * maritalStatus 
* Organization
   * type  
* All datatypes/extensions with eCH VS

**Comment by ziegm** [comment]
24.05.2023: FHIR Working Group agreed on the changes
