### ISSUE TITLE
Extension EPR Time - Add MedicationRequest.requester to context

### ISSUE THREAD

**Issue by dvribeira** [hl7ch/ch-core#238]
As per the subject, MedicationRequest.requester is missing from the context in input/fsh/extensions/EPRTime.fsh

**Comment by ziegm** [comment]
@dvribeira thanks for your input and your PR. Do you mean because of the description in CH EMED?
http://fhir.ch/ig/ch-emed/different-authors.html

**Comment by dvribeira** [comment]
@ziegm Yes it is related to that. I have another discussion that I have not yet found the time to trigger concerning the different authorships (document and medical) and their timestamps and how to manage them. But they belong to the CH-EMED project. I can already comment them here in case it adds any value to the issue:
The guidance in CH-EMED establishes that:

1. There is indeed a difference to be supported between a document author and a medical author.
2. Authorship is to be provided:
    - Within the composition (composition.author and, if different, composition.section.author) for provided documents and not within entries.
    - Within the entries (e.g. MedicationStatement.informationSource and, if different, MedicationStatement.extension.authorDocument)

Furthermore we draw the conclusion that authorship differs also if authorship timestamp differs and that this is to be supported with the references from:

- The IHE profiles: https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_MTP.pdf 
![261309675-a4db65a9-3221-4fa4-b77c-8babb03676ec](https://github.com/hl7ch/ch-core/assets/133101442/8c45ea56-8752-47e6-99c4-e8c04aaa5530)
- The time extension is specified explicitly for composition.author and for the documentAuthor extension.

I assumed the time extension could be used for all the informationSource equivalent elements of the entries and that would allow us to implement the authorship as described in the guidelines also taking into account authorship timestamp in a coherent and intuitive manner.

The alternatives would be to:

- Not consider authorhip timestamp but then I guess we should just use document timestamp and composition.author and documentAuthor have no need to display the time extension.
- Use fields already present in the entries. But this poses the question regarding why don't we use them when providing a document.

**Comment by ziegm** [comment]
30.08.2023:
12-0-0
