### ISSUE TITLE
CH Core Composition EPR (Gabriel Hess, BFH I4MI)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#242]
ch.fhir.ig.ch-core#4.0.0-ballot /StructureDefinition-ch-core-composition-epr.html

Bei type ist die Beschreibung "Kind of composition (LOINC if possible)", während das typeCode Valueset komplett aus Snomed CT Codes besteht.

Gabriel Hess, BFH I4MI

**Comment by ziegm** [comment]
Change: Update description of Composition.type for [CH Core Composition EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue242_descriptionCompositionType/StructureDefinition-ch-core-composition-epr.html)

@heg2 do you agree with this change?

**Comment by heg2** [comment]
> Change: Update description of Composition.type for [CH Core Composition EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue242_descriptionCompositionType/StructureDefinition-ch-core-composition-epr.html)
> 
> @heg2 do you agree with this change?

Yes, I do.

**Comment by ziegm** [comment]
30.08.2023:
12-0-0
