### ISSUE TITLE
New DataType CodeableConcept and Coding (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#245]
ch.fhir.ig.ch-core#4.0.0-ballot /StructureDefinition-ch-core-composition-epr.html

For fixed fixed coding values we need a defined DataType CodeableConcept and Coding do be able to define system/code as fixed and display as required but not defined with fixed display

Roeland Luykx (RALY GmbH)

**Comment by ziegm** [comment]
IPS does it with MustSupport:
https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-CodeableConcept-uv-ips.html
https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Coding-uv-ips.html

**Comment by ralych** [comment]
Makes perhaps no sense to do this.
why should display be required?
