### ISSUE TITLE
CH Core Document EPR: Bundle.identifier (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#246]
ch.fhir.ig.ch-core#4.0.0-ballot /StructureDefinition-ch-core-document-epr.html

Only allow a UUID as identifier for a Bundle in the EPR context
(https://datatracker.ietf.org/doc/html/rfc3986)

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Changes:
* Profile [CH Core Bundle EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue246_bundle-identifier/StructureDefinition-ch-core-document-epr.html)
* [Changelog](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue246_bundle-identifier/changelog.html)

**Comment by oliveregger** [comment]
Ok to proceed: 12 - 0 - 0
