### ISSUE TITLE
CH Core Document: constraint ch-core-doc-1 (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#247]
ch.fhir.ig.ch-core#4.0.0-ballot /StructureDefinition-ch-core-document.html

The fullUrl must be an absolute URL server address or an URI for UUID/OID
: startsWith('http') or startsWith('urn:uuid:') = true

The text isn't saying the same as the rule, it should be:
The fullUrl must be an absolute URL server address or an UUID

The expression can be refactored:
: startsWith('http') or startsWith('urn:uuid:')

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Changes:
* Profile [CH Core Document](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue247_fix-rule/StructureDefinition-ch-core-document.html)
* [Changelog](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue247_fix-rule/changelog.html)

**Comment by oliveregger** [comment]
Ok to proceed: 12 - 0 - 0
