### ISSUE TITLE
Errors with new bundle

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#255]
@ralych 
Please fix the errors/warnings with the new bundle (publisher version 1.5.4)

* Unable to find ImplementationGuide.definition.resource.description for the resource Immunization/9f326dee-1265-4b59-88b3-fd63bb2da934. Descriptions are strongly encouraged if they cannot be inferred from the resource to allow proper population of the artifact list.
* The link 'Immunization-TCA01-IMMUN1-patient.html' for "Immunization/TCA01-IMMUN1-patient" cannot be resolved
* and issues for Bundle-2-ResourceCrossReferencesDokument.json

**Comment by ralych** [comment]
PR: https://github.com/hl7ch/ch-core/pull/263
