### ISSUE TITLE
New extension to reference entries in i.e. other documents

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#262]
>New [extension](https://build.fhir.org/ig/hl7ch/ch-core/branches/master/StructureDefinition-ch-core-ext-entry-resource-cross-references.html) to reference entries in i.e. other documents

- fix errors in qa.html
- add it to the change log

Agree 13 - 2 - 0

**Comment by oliveregger** [comment]
clarification yes (13) - abstain (2) - no (0)

**Comment by ralych** [comment]
Reopend to simplify the extension by using the Reference DataType:
Change from subextensions with valueIdentifier and valueCode to valueReference with type and identifier as mandatory attributes
