### ISSUE TITLE
Missing constraint on number of identifers

### ISSUE THREAD

**Issue by jkiddo** [hl7ch/ch-core#269]
Currently, the CH Core Practitioner allow multiple (active) GLN's to be present. I don't think that is allowed by refdata.

**Comment by oliveregger** [comment]
Telco 6.12: add a warning constraint that only one active gln identifier should be provided.

**Comment by oliveregger** [comment]
active is not a flag on identifier, how should we check for active?

**Comment by oliveregger** [comment]
instead of active consider to ignore it with the usage old?

**Comment by oliveregger** [comment]
@jkiddo what do you consider as active? see comment above.

**Comment by jkiddo** [comment]
I guess `old` is fine.

**Comment by ziegm** [comment]
17.01.2024: Input from Lucas: we should ask the FOPH if one person can have more than one GLN -> Patrick will ask 
UC: if we have two different specialization for one practitioner (e.g. doctor and physiotherapist)

**Comment by pjolo** [comment]
The FOPH was unfortunately unable to answer my question. I asked refdata, which provides the GLN.

Answer from refdata: 
The GLN is a unique identifier and only one GLN exists per person. 
This can be linked to different work addresses or to different roles.
We confirm that there is only one GLN per person.

**Comment by jkiddo** [comment]
One 'official' that is?

**Comment by oliveregger** [comment]
@jkiddo we don't explicitly require 'official' as of yet
