### ISSUE TITLE
MaritalStatusECH011ToFHIRMapping Codierungsbeschreibung ergänzen

### ISSUE THREAD

**Issue by bfhksc1** [hl7ch/ch-core#3]
http://build.fhir.org/ig/hl7ch/ch-core/ConceptMap-maritalstatus-ech11-to-fhir.html
Es gibt ja ein Katalog bei welchem festgelegt ist, was hinter welchen Fall 1-9 steht, diese Beschreibung fehlt noch auf der angegebenen Seite.

Besonders der Spezialfall 5 (unverheiratet) der nur bei einer für ungültig erklärten Ehen oder verschollenen Ehepartner eintritt. Damit dieser Fall nicht mit ledig verwechselt wird.

Merci

**Comment by oliveregger** [comment]
Link zur Beschreibung der Definitionen der Codes hinzugefügt.
