### ISSUE TITLE
Original representation (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#300]
Updates to original representation, see https://github.com/hl7ch/ch-emed/issues/292, https://github.com/hl7ch/ch-emed/issues/300
https://chat.fhir.org/#narrow/stream/207835-IPS/topic/Referencing.20from.20IPS.20narrative.20to.20data

**Comment by oliveregger** [comment]
ready to integrate: 12 - 0 -0
