### ISSUE TITLE
Entry Resource Cross References, Usage/Description (Roeland Luykx,RALY GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#303]
ch.fhir.ig.ch-core#5.0.0-ballot /StructureDefinition-ch-core-ext-entry-resource-cross-references.html

Add more description for the usage of the extension.

Roeland Luykx (RALY GmbH)

**Comment by ralych** [comment]
relates to https://github.com/hl7ch/ch-vacd/issues/249

**Comment by ralych** [comment]
see ci-build: https://build.fhir.org/ig/hl7ch/ch-core/branches/303-entry-resource-cross-references-usagedescription-roeland-luykx-raly-gmbh/StructureDefinition-ch-core-ext-entry-resource-cross-references.html
