### ISSUE TITLE
New IG publisher warning about discriminator type 'pattern'

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#306]
`The discriminator type 'pattern' has been deprecated. Use type=fixed with a pattern[x] instead`
(note: this new warning message has a typo: It should say "Use type=value" instead of "Use type=fixed".)

https://build.fhir.org/valueset-discriminator-type.html:
**pattern**: _The slices have different values in the nominated element, as determined by the applicable fixed value, pattern, or required ValueSet binding. This has the same meaning as 'value' and is deprecated._

discussion on zulip:
- https://chat.fhir.org/#narrow/channel/179252-IG-creation/topic/deprecated.20pattern.20slicing
- https://chat.fhir.org/#narrow/channel/215610-shorthand/topic/'pattern'.20discriminator.20type.20deprecated

![image](https://github.com/user-attachments/assets/b8a1da4d-b105-4ce6-8df8-f9aed534a7b1)

TODO:
change `^slicing.discriminator.type = #pattern` to `^slicing.discriminator.type = #value`

**Comment by oliveregger** [comment]
Ok to integrate: 9 - 0 - 0
