### ISSUE TITLE
Snapshot Table displays duplicate elements in the element Identifier

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#31]
In the following profiles, the **sub-elements of the element identifier are displayed in duplicate** in the snapshot table:
https://fhir.ch/ig/ch-core/0.1.0/StructureDefinition-ch-core-organization.html
https://fhir.ch/ig/ch-core/0.1.0/StructureDefinition-ch-core-patient.html
https://fhir.ch/ig/ch-core/0.1.0/StructureDefinition-ch-core-composition-patient-epr.html

![grafik](https://user-images.githubusercontent.com/32767151/75232770-0f44fd80-57b8-11ea-83f3-f3fa7c472237.png)

Applied **slicing**:
```
<slicing>
   <discriminator>
      <type value="pattern" />
      <path value="$this" />
   </discriminator>
   <rules value="open" />
</slicing>
```

Applied **pattern**:
```
<patternIdentifier>
   <system value="urn:oid:2.16.756.5.45" />
</patternIdentifier>
```

**No duplicates** are displayed without the following code element:
```
<element id="Organization.identifier:BER.value">
   <path value="Organization.identifier.value" />
   <short value="BER of the organization" />
   <definition value="BER of the organization"/>
   <min value="1" />
</element>
```

**Comment by DavidGutknecht** [comment]
Hello Michaela, 

I'm really not an expert in slicing, but did you try with a different kind of discriminator like ?

```
<discriminator>
	<type value="value"/>
        <path value="system"/>
</discriminator>
<discriminator>
        <type value="value"/>
        <path value="code"/>
</discriminator>
```
				


Best regards,
David

**Comment by ziegm** [comment]
Dear David

Thanks for your input.

![image](https://user-images.githubusercontent.com/32767151/81080080-a3d28700-8ef0-11ea-9fc6-fb4154f318d0.png)

You can see from the example of the Patient.identifier that the discriminator should be pattern, because the identifier:LocalPid is built differently than the others.

Best regards,
Michaela

**Comment by DavidGutknecht** [comment]
Thanks for the explanation !

Just another supposition.
LocalPid has cardinality 0..*
But the pattern identifier is fix
![grafik](https://user-images.githubusercontent.com/26225925/81083625-1b0a1a00-8ef5-11ea-81ed-27645bf73cee.png)

This would mean that the system will not be able to distinguish between two LocalPid.
You should somehow also include the system and the value or ?

Best regards, 
David

**Comment by oliveregger** [comment]
System and value are set to 1 for identifier:LocalPID, so you can distinguish between different LocalPID's according to system. The slice however identifies all localPID's together, thats intended. 

The origin of this issue is that the html representation in the implementation guide is not correct, the snaphshot which is generated however is correct.

**Comment by DavidGutknecht** [comment]
Hello, 
just as information, I solved this duplicate on my side by doing as following:
For example line 199 <element id="Patient.identifier:LocalPid">
If you remove the patternIdentifier
````
 <patternIdentifier>
                <type>
                    <coding>
                        <system value="http://terminology.hl7.org/CodeSystem/v2-0203" />
                        <code value="MR" />
                    </coding>
                </type>
            </patternIdentifier>
````
And if you fix the "system" and the "code" in separated elements:
````
		<element id="Patient.identifier:LocalPid.type.coding.system">
			<path value="Patient.identifier.type.coding.system" />
			<fixedUri value="http://terminology.hl7.org/CodeSystem/v2-0203"/>
		</element>
		<element id="Patient.identifier:LocalPid.type.coding.code">
			<path value="Patient.identifier.type.coding.code" />
			<fixedCode value="MR"/>
		</element>
````

It should do the Trick, and nomore duplicate in the html the "system" part.
I'm not sure that the signification is the same. But from the look and feel point of view it looks ok ;-)

Best regards,
David

**Comment by oliveregger** [comment]
we need to use the patternIdentifier otherwise the slicing will not work with the different identifier usecases. can you validate with your setup all the examples?

**Comment by DavidGutknecht** [comment]
You are right, after validating throw the examples I got some errors :-(
Sorry for the disturbing.

**Comment by ziegm** [comment]
Changes: ONGOING!
* Define min. card. of identifier.value for all slices once instead of defining it for each slice separately (not necessary to define explicitly for identifier.system because of the existing rule: )
   * same validation
   * no duplicated elements in the snapshot table -> better readability of profiles
* Profiles
   * [ch-core-organization]()
   * [ch-core-patient]()
* [Change log]()

**Comment by oliveregger** [comment]
Telco vom 1.3: 12 - 0 - 0
