### ISSUE TITLE
Patient.maritalStatus (unvollständiges ValueSet für getrennt lebend, Konkubinat und Polygamie)

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#35]
Emmanuel Eschmann:

- Das ValueSet http://fhir.ch/ig/ch-core/ValueSet/ch-core-maritalstatus führt nur die Haupt-Zivilstände gemäss «BFS Amtlicher Katalog der Merkmale» (https://www.bfs.admin.ch/bfsstatic/dam/assets/349276/master) S. 26 auf. Das Teilmerkmal «Trennung» fehlt jedoch in unserem ValueSet (z.Bsp. «getrennt lebend», was z.Bsp. für die allfällige Kontaktaufnahme mit dem noch verheirateten Partner relevant ist).

- Das ValueSet http://fhir.ch/ig/ch-core/ValueSet/ch-core-maritalstatus führt nur die Schweizer Zivilstände auf. Für Ausländer, die sich in der Schweiz behandeln lassen fehlen die Zivilstände ihrer Länder wie Konkubinat und Polygamie.

**Vorschlag**: 
Ergänzen des ValueSets http://fhir.ch/ig/ch-core/ValueSet/ch-core-maritalstatus um getrennt lebend, Konkubinat und Polygamie

**Comment by oliveregger** [comment]
Trennung: Das Teilmerkmal Trennung differenziert ja die einzelnen Values von maritalStatus 

> Teilmerkmal 343 Trennung (obligatorisch bei verheirateten und getrennt lebenden Personen und bei in eingetragener Partnerschaft und getrennt lebenden Personen)

wäre eine eigene Extension sein mit ValueSet/CodeSystem.

Konkubinat und Polygamie sind im ch-core-maritalstatus eingebunden über das Codesystem.
Import all the codes that are contained in http://hl7.org/fhir/ValueSet/marital-status 

Polygamie -> P
Konkubinat -> T?

siehe auch ConceptMap: https://fhir.ch/ig/ch-core/ConceptMap-maritalstatus-ech11-to-fhir.html

**Comment by oliveregger** [comment]
Teilmerkmal Trennung erarbeiten in 0.2.0: 9 - 0 - 0

**Comment by oliveregger** [comment]
Vorschlag Emmanuel Eschmann:

zur Auflösung der Rückmeldung:

«Patient.maritalStatus (unvollständiges ValueSet für getrennt lebend, Konkubinat und Polygamie)» (https://github.com/hl7ch/ch-core/issues/35)
URL des betroffenen ValueSets:

http://build.fhir.org/ig/hl7ch/ch-core/ValueSet-ch-core-maritalstatus.html
Zsfg Problemstellung:

A: Das ValueSet http://fhir.ch/ig/ch-core/ValueSet/ch-core-maritalstatus führt nur die Haupt-Zivilstände gemäss «BFS Amtlicher Katalog der Merkmale» (https://www.bfs.admin.ch/bfsstatic/dam/assets/349276/master) S. 26 auf. Das Teilmerkmal «Trennung» fehlt jedoch in unserem ValueSet (z.Bsp. «getrennt lebend», was z.Bsp. für die allfällige Kontaktaufnahme mit dem noch verheirateten Partner relevant ist).
bereits aufgelöste Problemstellung B: Konkubinat und Polygamie sind bereits in http://fhir.ch/ig/ch-core/ValueSet/ch-core-maritalstatus eingebunden über das Codesystem http://terminology.hl7.org/CodeSystem/v3-MaritalStatus:
Polygamie: P (Polygamous: More than 1 current spouse)
Konkubinat: T (Domestic partner: Person declares that a domestic partner relationship exists)
Vorschlag:

Bemerkung: «getrennt lebend» bildet eigentlich ein Teilmerkmal der bestehenden maritalstatus-ValueSet-Einträge «verheiratet» und «in eingetragener Partnerschaft» ab. Da mir nicht bekannt ist, wie solche Teilmerkmale in FHIR modelliert werden sollen, resultiert nachfolgender Vorschlag mit einer «specializes» - Beziehung der neuen zu bestehenden Einträgen.
Definition eines neuen CodeSystems «ch-core-maritalstatus-separated»:
mit den beiden Einträgen:
«verheiratet, getrennt lebend»
«in eingetragener Partnerschaft, getrennt lebend»
Einbindung dieses neuen CodeSystems in das ValueSet http://build.fhir.org/ig/hl7ch/ch-core/ValueSet-ch-core-maritalstatus
Mapping der beiden Einträge des neuen CodeSystems über zwei neue Einträge in der bestehenden ConceptMap http://fhir.ch/ig/ch-core/ConceptMap/maritalstatus-ech11-to-fhir:
«verheiratet, getrennt lebend» «specializes» «verheiratet»
«in eingetragener Partnerschaft, getrennt lebend» «specializes» «in eingetragener Partnerschaft»

**Comment by ziegm** [comment]
Als Ergänzung Vergleich mit dem deutschen Basisprofil:

Getrennt lebend wird mit dem Code **L = getrennt lebend**, äquivalent zu zum FHIR ValueSet abgebildet. "Getrennt lebend" ist somit kein Teilmerkmal.
- DE: https://simplifier.net/guide/basisprofil-de-r4/marital-status
  L = getrennt lebend
- FHIR: http://hl7.org/fhir/R4/valueset-marital-status.html
  L = Legally Separated

**Comment by oliveregger** [comment]
Gemäss BFS ist getrennt lebend ein Teilmerkmal. Teilmerkmal 343 Trennung (obligatorisch bei verheirateten und getrennt lebenden Personen und bei in eingetragener Partnerschaft und getrennt lebenden Personen) und hat die Werte 1 Freiwillig getrennt sowie 2 Gerichtlich getrennt.

Falls wir das abbilden wollen, würde ich einen Extension vorschlagen in maritialStatus die explizit die Trennung Codes beinhaltet:

  "maritalStatus" : {
     "extension" : [
       {
        "url" : "http://hl7.org/fhir/StructureDefinition/ech-11-maritalData-separation",
        "valueCodeableConcept" : {
         "coding" : [
            {
             "system" : "http://fhir.ch/ig/ch-core/CodeSystem/ech-11-separationType",
              "code" : "1",
             "display" : "Freiwillig getrennt"
           }
         ]
       }
     }
    ],
    "coding" : [
      {
        "system" : "http://fhir.ch/ig/ch-core/CodeSystem/ech-11-maritalstatus",
        "code" : "6",
        "display" : "in eingetragener Partnerschaft"
      }
    ]
  },

**Comment by oliveregger** [comment]
1) Weil das HL7 ValueSet Extensible ist, muss der v3-MaritalSatus ValueSet angegeben werden wenn vorhanden (siehe auch http://fhir.ch/ig/ch-core/Patient-ElisabethBroennimannByBFH.json.html)
2) Teilmerkmal Trennung als Extension von maritalStatus definieren gemäss obigem Beispiel.
     - Neues CodeSystem, neues ValueSet
     - Extension

Vorschlag angenommen: 7-0-0

**Comment by oliveregger** [comment]
- Hinzufügen bei maritalStatus Element bei Patient
- eCH-011 maritaldata-separation -> Naming an andere eCH CodeSystem/ValueSets angleichen
