### ISSUE TITLE
Patient: Religion: unvollständiges ValueSet

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#36]
Emmanuel Eschmann
- http://fhir.ch/ig/ch-core/ValueSet/ech-11-religion führt mit 1 reformierten, 2 katholischen und 3 jüdischen Konfessionen nur sehr wenige Konfessionen und Religionen auf.
- Das Wissen um den Glauben des Patienten ist im Spital relevant (z.Bsp. für Aufbieten der korrekten Seelsorge bei Komplikationen).
- Folge das sehr unvollständigen ech-11-ValueSets: Die Schweizer Systeme verwenden das vollständigere ValueSet http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation (wird durch die Extension ChCorePatientReligion nicht verhindert).

**Vorschlag**
Verbleib beim vollständigeren ValueSet http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation und Verzicht auf ein Schweizer ValueSet.

**Comment by oliveregger** [comment]
Background: https://github.com/hl7ch/ch-core/issues/18

**Comment by oliveregger** [comment]
Persuasive to remove extension ch-core religion (http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-patient-religion.html) valueset ech11 for religion for mapping could stay, http://hl7.org/fhir/extension-patient-religion.html will be used for the swiss core-patient.

9 - 0 - 0

**Comment by oliveregger** [comment]
Verwendung des HL7-CodeSystems anstelle des unvollständigen Schweizer CodeSystemsValueSet für Religion: Verwendung des HL7-CodeSystems anstelle des unvollständigen Schweizer CodeSystems
zur Auflösung der Rückmeldung:

«Patient: Religion: unvollständiges ValueSet)» (https://github.com/hl7ch/ch-core/issues/36)
URL des betroffenen ValueSets:

http://build.fhir.org/ig/hl7ch/ch-core/ValueSet-ech-11-religion.html
Zsfg Problemstellung:

Issue ist bereits closed mit dem Beschluss «Persuasive to remove extension ch-core religion (http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-patient-religion.html) valueset ech11 for religion for mapping could stay, http://hl7.org/fhir/extension-patient-religion.html will be used for the swiss core-patient.» und in «CHCorePatient»  (http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-patient.html) nachgeführt, allerdings findet sich die dadurch obsoleten CH-ValueSets und -CodeSystems für Religion noch auf FHIR.ch (http://build.fhir.org/ig/hl7ch/ch-core/ValueSet-ech-11-religion und http://fhir.ch/ig/ch-core/CodeSystem/ech-11-religion)
Vorschlag:

http://build.fhir.org/ig/hl7ch/ch-core/ValueSet-ech-11-religion und http://fhir.ch/ig/ch-core/CodeSystem/ech-11-religion entfernen

**Comment by ziegm** [comment]
Zusätzlich du dem ValueSet und dem CodeSystem müsste noch Folgendes gelöscht werden:

- Mapping: http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-patient-mappings.html#mappings-for-ech-standards-http-www-ech-ch

extension (religion) | eCH-0011: 3.3.4.1 religion, BFS-711
-- | --

- ConceptMap: http://build.fhir.org/ig/hl7ch/ch-core/ConceptMap-religion-ech11-to-fhir.html

**Comment by oliveregger** [comment]
CDA-CH hat das Mapping definiert zwischen eCH und HL7V3: http://e-health-wiki.ch/index.php/Ehscda:CDA-CH_V2.1_2020_(specification)#Mapping_zu_eCH-0011_religion_.E2.80.93_Konfessionszugeh.C3.B6rigkeit

**Comment by oliveregger** [comment]
Emmanuels Vorschlag CodeSystem/ValueSet sowie Mapping zu eCH-0011 löschen: 8 - 0 -0

**Comment by oliveregger** [comment]
needs to be merged into ci
