### ISSUE TITLE
PractitionerRole.code: unvollständiges Valueset

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#44]
Walter Wellauer:

- In den HL7v2 ADT Nachrichten zwischen Admin- und z.B. KIS Systemen werden auch prozessorientierte Rollen von Gesundheitsfachpersonen ausgetauscht wie z.B. Hausarzt, einweisender Arzt, behandelnder Arzt, mitbehandelnder Arzt, Belegarzt o.ä.
- Wenngleich das Binding nur (preferred) auf HCProfessional.hcProfession ist, so ist sein Werteset doch schon viel eingeschränkter als in http://hl7.org/fhir/R4/valueset-practitioner-role.html, wo man zumindest für den Hausarzt mit dem general practitioner oder family medicine specialist eine in etwa Entsprechung

**Vorschlag** Erweiterung des value sets um die prozessorientierten Rollen oder (da code card. O..*) Angebot eines zusätzlichen  prozessorientierten valuesets, und/oder feedback in die Patient Administration Workgroup, wo das maturity level offenbar noch 1 ist.

**Comment by oliveregger** [comment]
Frage: Sind  http://hl7.org/fhir/R4/valueset-practitioner-role.html prozessorientierte Rollen? Wäre das ADT Nachrichten äquivalent nicht der Encounter.participant.type? (http://hl7.org/fhir/R4/encounter.html)

**Comment by oliveregger** [comment]
Walter: PV1.segment

**Comment by oliveregger** [comment]
Mapping HL7v2 to FHIR https://docs.google.com/spreadsheets/d/1Sqt8f_LpBVMIdJxcAlB4emDOBqXV8rhy60V2_yaDp7c/edit#gid=0

Mapping PV1 Segment: https://docs.google.com/spreadsheets/d/1Sqt8f_LpBVMIdJxcAlB4emDOBqXV8rhy60V2_yaDp7c/edit#gid=0

![image](https://user-images.githubusercontent.com/2414516/77304308-88bb0780-6cf4-11ea-822d-3d62f6db2703.png)

TBD: Prozessorientierte Rollen in Encounter abbilden.

**Comment by oliveregger** [comment]
Hausarzt, der als funktionsbezogene Rolle der im Encounter.participant.type verwendet werden kann mit PCP (primary care physician) aus ParticipationFunction von HL7 Inc: 2.16.840.1.113883.5.88
Neues ValueSet für Encounter.participant.type basierend auf http://hl7.org/fhir/R4/valueset-encounter-participant-type.html das den PCP Code ergänzt.

Ja 9: Enthaltung: 0 Nein: 0

**Comment by oliveregger** [comment]
https://www.hl7.org/fhir/v3/ParticipationFunction/cs.html

**Comment by walterwellauer** [comment]
Oliver: Code in das ValueSet http://build.fhir.org/ig/hl7ch/ch-core/branches/stu0.1.0/ValueSet-ch-core-encounter-participation-type.html eingebaut und
verlinkt vom Ch Core Encounter: http://build.fhir.org/ig/hl7ch/ch-core/branches/stu0.1.0/StructureDefinition-ch-core-encounter.html
Walter: das ist gut so für mich und ich ziehe damit den negativen Kommentar im Balloting-Verfahren zurück.
