### ISSUE TITLE
IPS (International Patient Summary) Einfluss auf STU2

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#55]
- Status Allergie - Publikation der IPAG
- Problemliste - Diagnosen
- Medikation

Abbildung in CH-Core oder davon abgeleitete Implmentierungsleitfäden

**Comment by oliveregger** [comment]
IPA - International Patient Access -> Subset des IPS (Dokumentenbasiert)

**Comment by ziegm** [comment]
@oliveregger as we started to work on the CH IPS we can close this issue?
https://build.fhir.org/ig/hl7ch/ch-ips/index.html
