### ISSUE TITLE
ch-core-patient/Patient.identifier:LocalPid.type.coding.code - Remark

### ISSUE THREAD

**Issue by DavidGutknecht** [hl7ch/ch-core#56]
Hello, 

In the Profile ch-core-patient, I just saw that the Patient.identifier:LocalPid.type.coding.code has value MR that means "Medical Record" according to http://hl7.org/fhir/v2/0203/.
This list also contain the code PI that means "Patient internal identifier".

I compared the two descriptions:
PI = A number that is unique to a patient within an Assigning Authority.
MR = An identifier that is unique to a patient within a set of medical records, not necessarily unique within an application.

In my opinion MR would corresponds more to a Visit-Nr than to a local Patient Id and PI would better fit here.
What do you think ?

Best regards,
David

**Comment by oliveregger** [comment]
thank you for the feedback! we discussed it during the development, because PI is not in the FHIR ValueSet we (HL7 fhir.ch workgroup) settled for "MR" (the german way :-)), see https://github.com/hl7ch/ch-core/issues/6 for more info.

**Comment by DavidGutknecht** [comment]
Thanks for the clear Answer !
