### ISSUE TITLE
Kardinalität SetId & VersionNumber

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#57]
Kardinalität der SetId & VersionNumber ändern von 1..1 auf 0..1 für die FHIR-Dokumente.

Zu änderndes Profil: [CH Core Composition EPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/master/StructureDefinition-ch-core-composition-epr.html)

Elemente kommen aus der CDA-Spezifikation und sind in den CDA-Dokumenten required. Wenn ein FHIR-Dokument in ein CDA-Dokument transformiert wird, soll die SetId (Value of Bundle.identifier) und die VersionNumber = 1 generiert werden.

**Comment by oliveregger** [comment]
Änderung machen: 8 - 0 - 0
