### ISSUE TITLE
Typo bei Encounter.class

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#58]
Im Profil [CH Core Encounter](http://build.fhir.org/ig/hl7ch/ch-core/branches/master/StructureDefinition-ch-core-encounter.html) hat es einen Typo:

- INP sollte **IMP** sein
- AMB | INP : See mapping from BFS Medizinische Statistik BFS Encounter Class to FHIR

In der dazugehörigen [ConceptMap](http://build.fhir.org/ig/hl7ch/ch-core/branches/master/ConceptMap-bfs-encounter-class-to-fhir.html) ist es korrekt.

**Comment by oliveregger** [comment]
so anpassen: angenommen 8-0-0

**Comment by oliveregger** [comment]
zusätzlich in der Textbeschreibung den Typo See mapping from BFS **Medizinsiche** Statistik BFS Encounter Class to FHIR
