### ISSUE TITLE
Extension InformationRecipient

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#59]
Input Emmanuel (Telco 29.06.2020):
Issue mit CH Core-Extension http://fhir.ch/ig/ch-core/StructureDefinition-ch-ext-epr-informationrecipient.html
- sollten die nicht auf CH-Core Profile referenzieren?
- Device auch notwendig?

**Comment by ziegm** [comment]
Die Extension ist entstanden, um im EPD-Kontext das CDA-Element Information Recipient abbilden zu können.
https://art-decor.org/art-decor/decor-templates--hl7chcda-?section=templates&id=2.16.756.5.30.1.1.10.2.4&effectiveDate=2018-04-18T00:00:00&language=en-US

1) Referenz CH Core Profile?
   - Die CH Core-Profile sind bezüglich den Kardinalitäten zu streng. Zum Beispiel beim [CHCoreCompositionPatientEPR](http://build.fhir.org/ig/hl7ch/ch-core/branches/master/StructureDefinition-ch-core-composition-patient-epr.html) wird ein Identifiert verlangt, welcher im CDA-Dokument nicht zwingend enthalten sein muss.
   - CDA verlangt keine spezifischen Elemente der Person/Organization, daher wurde auf die FHIR-Basisprofile referenziert.

2) Referenz zu Device notwendig?
   - Ich würde sagen nein. In der CDA-Spezifikation wird auf CDA Person und CDA Organization referenziert.

**Comment by oliveregger** [comment]
Issue mit CH Core-Extension http://fhir.ch/ig/ch-core/StructureDefinition-ch-ext-epr-informationrecipient.html
1.) Abklären ob es für http://fhir.ch/ig/ch-core/StructureDefinition-ch-ext-epr-informationrecipient.html geht mit Referenz auf ch-core-patient
2.) Referenz auf http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition-patient-epr.html

**Comment by ziegm** [comment]
Antwort Frage 1: ja, ist möglich
Bemerkung Frage 2: Patient.identifier 1..*, somit ich dieses Profil nicht sinnvoll zu referenzieren

Beschreibung der Extension:   
Extension for a recipient of this document (corresponds to the **addressee of a letter** - person or organization), equivalent to CDA informationRecipient.

Aktuelle Referenzen -> Bemerkung => Vorschlag:
* Practitioner -> CHCorePractitionerEPR identifier 1..1, daher ungeeignet => CHCorePractitioner
* Device -> passt nicht zur Beschreibung (person or organization) => Referenz entfernen
* Patient -> CHCoreCompositionPatientEPR identifier 1..1, daher ungeeignet => CHCorePatient
* RelatedPerson -> ok => so belassen
* PractitionerRole -> CHCorePractitionerRole hat keine Adresse, ist als Referenz daher ungeeignet => Referenz entfernen
* Organization

**Comment by oliveregger** [comment]
Entsprechend so anpassen: 10 - 0 - 0
