### ISSUE TITLE
Kardinalitäten im CH Core Organization Profil zu streng?

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#60]
Profil: [CH Core Organization](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-organization.html)

Die Minimumkardinalität der Elemente **identifier** und **name** sind auf 1 gesetzt worden. Dies führt dazu, dass das Ableiten dieses Profils nicht für alle Anwender möglich ist. Gibt es einen Grund, wieso diese Angaben required sind? 

Recherche zu möglichen Gründen:
* Wurde beim ersten Commit ([Git History](https://github.com/hl7ch/ch-core/commit/202b7928da48a1ad7aeef656ffabcb63f98dd608#diff-29e8de1e1d84192bc3984527ed84ebbc)) so abgebildet.
* Angewendete eCH-Standards haben meiner Meinung nach keinen Einfluss ([eCH-0010 Postadresse](https://www.ech.ch/vechweb/page?p=dossier&documentNumber=eCH-0010&documentVersion=7.0), [eCH-0011 Personendaten](https://www.ech.ch/vechweb/page?p=dossier&documentNumber=eCH-0011&documentVersion=8.1)).
* CDA-CH bildet die Organization verschieden ab, d.h. mit unterschiedlichen Minimumkardinalitäten. Einzig das Element **name** ist überall required, siehe [hier](https://art-decor.org/art-decor/decor-templates--hl7chcda-?section=templates&id=2.16.756.5.30.1.1.10.9.24&effectiveDate=2018-04-18T00:00:00&language=en-US). 
* Spezifikation FHIR: *org-1: The organization SHALL at least have a name or an identifier*

Diskussion:
Kann ein Konsens gefunden werden, dass man die Minimumkardinalität von Organization.identifier auf 0 setzt? FHIR verlangt identifier oder name, da CDA name immer fordert, könnte man das Element name verlangen.

**Comment by oliveregger** [comment]
walter. ich bin dafür es vom Standard zu übernehmen (name und id als 0): 10 - 0 -0
