### ISSUE TITLE
CH-Encounter: specify a type for the visit number Fallnummer

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-core#66]
The visitnumber (german: Fallnummer) is defined in the [Encounter](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-encounter.html) as an identifier . To enable to differentiate the visitnumber for different identifiers
we suggest to add a type following the same way as we did for the [swiss patient profile](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-patient.html) with the identifier:LocalPid using the [VN](http://hl7.org/fhir/R4/v2/0203/index.html) code.

```xml
<identifier>
    <type>
        <coding>
            <system value="http://terminology.hl7.org/CodeSystem/v2-0203" />
            <code value="VN" />
        </coding>
    </type>
    <system value="http://www.example.ch/fallnummerdomain"/>
    <value value="eindeutige Fall-Identifikation"/>
</identifier>
```

**Comment by oliveregger** [comment]
agree - 11 - abstain - 0 - negative -0

**Comment by ziegm** [comment]
Updated Profile: http://build.fhir.org/ig/hl7ch/ch-core/branches/master/StructureDefinition-ch-core-encounter.html
Updated Example: http://build.fhir.org/ig/hl7ch/ch-core/branches/master/Encounter-EncounterAmbulantBroennimann.xml.html
