### ISSUE TITLE
EPRDataEnterer: valueReference only to Practitioner (not Person)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-core#85]
**CH Core Extension [EPRDataEnterer](http://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-ext-epr-dataenterer.html)**

Definition: Extension to define the information about the person that entered data and the time of the data input, equivalent to the dataEnterer from a CDA document

The extension currently references *CH Core Practitioner Profile* and *Person*. The reference to Person should be removed.
* FHIR Spec [Person](http://hl7.org/fhir/R4/person.html): *Person instances are never directly referenced as actors (authors, subjects, performers, etc.) Individual actors are always identified as either Patient, Practitioner or RelatedPerson, depending on the role of the individual when undertaking the action.*
* What we want to represent, we can map in the Practitioner.
   * FHIR Spec [Practitioner](http://hl7.org/fhir/R4/practitioner.html): *Practitioner covers all individuals who are engaged in the healthcare process and healthcare-related services, e.g. physicians, pharmacists, physician assistants, nurses, scribes, therapists, receptionists handling patient registration, IT personnel merging or unmerging patient records*

**Comment by oliveregger** [comment]
Remove the Person: 12 -0 - 0
