### ISSUE TITLE
EPR Data Enterer (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#91]
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-ext-epr-dataenterer.html

Beim "enterer" noch die PractitionerRole als valueReference ergänzen. So kann ein Practitioner auch über die PractitionerRole abgebildet werden, und zusätzlich wird ermöglicht, dass die Organization referenziert werden kann. Dieses Konzept wird z.B. im CH ORF verfolgt.

Michaela Ziegler, ahdis ag

**Comment by oliveregger** [comment]
replaced with PractitionerRole instead of Practitioner
