### ISSUE TITLE
Human Name (Emmanuel Eschmann (CISTEC AG))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#94]
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-core-humanname.html

Beschreibung zur Prefix-Extension in Übereinstimmung bringen mit dem Beschluss vom 8.6.2020 in https://github.com/hl7ch/ch-core/issues/34, d.h.: «For academical titles and legal status use the http://hl7.org/fhir/ExtensionDefinition/iso21090-EN-qualifier with the codes AC, LS. For a salutation use a prefix without an the iso21090-EN-qualifier extension.»

Emmanuel Eschmann (CISTEC AG)

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/stu2ballotprefix/StructureDefinition-ch-core-humanname.html
