### ISSUE TITLE
EPR Set ID, identifier needs to be fixed to uuid (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#96]
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-ext-epr-setid.html

CDA-CH documents are uniquely identified by an uuid. That we can map between CDA and FHIR and that we can transform a specific version (setID) we should fix the valueIdentifier.system to a uuid, corresponding to https://github.com/hl7ch/ch-core/issues/95

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
removed, see #97
