### ISSUE TITLE
CH Core Composition Profile EPR (Michaela Ziegler (ahdis ag))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#97]
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-core-composition-epr.html

What is the purpose of the Composition.identifier? Currently, the Composition.identifier and the Bundle.identifier have the same value (see [example](http://fhir.ch/ig/ch-emed/Bundle-2-7-MedicationCard.html)). Does that make sense?

Michaela Ziegler (ahdis ag)

**Comment by ziegm** [comment]
The format should be the same as the Bundle.identifier:
https://github.com/hl7ch/ch-core/issues/95

**Comment by oliveregger** [comment]
fhir spec says:

> A composition is a logical construct- its identifier matches to the CDA ClinicalDocument.setId.
> http://hl7.org/fhir/composition.html#cda

Suggest to remove the EPR Set ID extension and restrict Composition.identifier to a uuid (see #95)
