### ISSUE TITLE
Konsistenten Namensgebung: CH Core ***Composition**** Patient Profile EPR: "Composition" sollte durchgestrichen sein: "Durchstreichen" ging bei Copy Paste in Comment verloren 

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-core#98]
Changeproposal im Sinne einer konsistenten Namensgebung:

CH Core Patient Profile
CH Core Composition Patient Profile EPR

CH Core Composition Profile
CH Core Composition Profile EPR

CH Core Document Profile
CH Core Document Profile EPR

CH Core DocumentReference Profile
CH Core DocumentReference Profile EPR

CH Core Organization Profile
CH Core Organization Profile EPR

CH Core Practitioner Profile
CH Core Practitioner Profile EPR

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/stu2ballot-patient/profiles.html
