### ISSUE TITLE
Define mustSupport for CH-Core (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#99]
ch.fhir.ig.ch-core#1.2.0 /

mustSupport behaviour is not defined for this implementation guide, this should be defined 

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
Definition von IHE nimmt als Basis für R2:
- http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/index.html#conformance-expectations

**Comment by oliveregger** [comment]
Stand heute AllergieIntoleranz: mustSupport Kreuzprodukt zwischen IPS und IPAG, nicht MinimalDataSet wie bei eMedikation

**Comment by oliveregger** [comment]
https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Developments#use-of-must-support
